version: "4.19"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: app:react
    container_name: tasktracker_container
    command: npm start